2018-11-16 18:17:28,560 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-16 18:17:40,057 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-16 18:17:49,546 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-17 11:58:50,622 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-17 11:58:53,752 ERROR: Exception on /login [GET] [in /home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/araris/Documents/gear_compare/app/errors/handlers.py", line 7, in not_found_error
    return render_template('404.html'), 404
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/araris/Documents/gear_compare/v_env/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
2018-11-21 12:37:09,306 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-21 13:03:59,956 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-21 13:04:09,321 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 16:21:00,719 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 16:44:43,207 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 16:44:54,488 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 17:53:24,102 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 17:53:30,568 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 19:00:29,618 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 19:00:32,296 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:19:58,538 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:22:32,535 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:29:00,510 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:29:13,139 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:30:09,091 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:30:10,865 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:36:51,914 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:39:59,340 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
2018-11-26 23:40:02,108 INFO: gear_compare startup [in /home/araris/Documents/gear_compare/app/__init__.py:48]
